services:
  chromadb:
    image: chromadb/chroma
    ports:
      - 3003:8000
    container_name: chromadb
    networks:
      - net

  init:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: init-data
    depends_on:
      chromadb:
        condition: service_started
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - LOGGING_LEVEL=INFO
      - CONFIG_PATH=config.json
    networks:
      - net

networks:
  net:
    external: true
